extends Node

onready var tex_cue_ball = load("res://assets/images/balls/cue_ball.png")
onready var tex_black_full_8 = load("res://assets/images/balls/black_full_8.png")
onready var tex_blue_full_2 = load("res://assets/images/balls/blue_full_2.png")
onready var tex_blue_half_10 = load("res://assets/images/balls/blue_half_10.png")
onready var tex_brown_full_7 = load("res://assets/images/balls/brown_full_7.png")
onready var tex_brown_half_15 = load("res://assets/images/balls/brown_half_15.png")
onready var tex_green_full_6 = load("res://assets/images/balls/green_full_6.png")
onready var tex_green_half_14 = load("res://assets/images/balls/green_half_14.png")
onready var tex_orange_full_5 = load("res://assets/images/balls/orange_full_5.png")
onready var tex_orange_half_13 = load("res://assets/images/balls/orange_half_13.png")
onready var tex_purple_full_4 = load("res://assets/images/balls/purple_full_4.png")
onready var tex_purple_half_12 = load("res://assets/images/balls/purple_half_12.png")
onready var tex_red_full_3 = load("res://assets/images/balls/red_full_3.png")
onready var tex_red_half_11 = load("res://assets/images/balls/red_half_11.png")
onready var tex_yellow_full_1 = load("res://assets/images/balls/yellow_full_1.png")
onready var tex_yellow_half_9 = load("res://assets/images/balls/yellow_half_9.png")
